import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'

export const myFont = localFont({
  src: '../../public/assets/fonts/FontsFree-Net-gotham-ultra.ttf',
  display: 'swap',
})

export const inter = Raleway({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
